apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kostnidren-uptime-probe
  description: 'Uptime probe (public)'
  annotations:
    github.com/project-slug: hozantaher/kostnidren-uptime-probe
  tags:
    - ops
  links:
    - url: https://github.com/hozantaher/kostnidren-uptime-probe
      title: Repo
      icon: github
    - url: https://event-bus-production.up.railway.app/net
      title: Živá pavučina (Indra odraz)
      icon: dashboard
spec:
  type: library
  lifecycle: production
  owner: hozantaher
  system: ops
